language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-stable
  - Pharo64-stable

notifications:
  slack:
    secure: cUf+zRp8lIme3PwVrkiekE1sEjy/hId2USEipXboYvJi7PP8oKzFsA/jkMQUzrvPS85g5OGe87so9gDKOpq55+Pi2TzAHhMKHk/U5R1/w0Y64UhI9GTteiNfUTSNHnN+Z5DlkTolq0oyRyIYbk7ycbFaFt/d2v1lmlPHKsQHX+XEB3/VsZXeWh3X7lui3TN5ty0OEenXpXTSMSDErnBy3dVNYIdLcxTJExpGfGBC7OxOcTHZIktvJU4oQlDpRlGemqpSiRkOghcW69lCJpiGLx7OD839CnkZ0f587lCmnyuk0lKJ5BJqlFuxtNM6Cl/A/POgupVLeKBXtnIj3DuneV5fDas6JkHjWqjovaxdwVNpODySZSlS50Y/7Ls4XlEIb762l08CE6c900K9D+U+Mrpt22cGQmPqPJny+7AdUkQXZnqq5dmj1QQQLodgPwEYA5ogMfPBU5/dXWltOtZq0wWKFUNQlXG7aXLsCHFzF7iZRSyOAgJGovdvgtniUF3c1Je2gxTZl6lzOqGXIEZ/YO5B87aiUrhuofw90UAsOwbnEKrz0PO+6HvmhEd5EyeLD0zr1NQADoN2wiC4O6O+iCZG+87l5wJVLovYB4ZgDOKrirnipCRpsn+bk7pGILRpPdug31xCXzlerrxBDMjFJtBd1uIJ9o+r9Bq00wmsbas=